export enum ERole {
  ROLE_ADMIN = "ROLE_ADMIN",
  ROLE_CHARGEE = "ROLE_CHARGEE",
  ROLE_CHEFDEPARTEMENT = "ROLE_CHEFDEPARTEMENT" ,
  ROLE_CHEFDIVISION = "ROLE_CHEFDIVISION",
  ROLE_USER = "ROLE_USER",

}
